### ISSUE TITLE
memory-fs是node_modules里面自带的好么？

### ISSUE THREAD

**Issue by jsm1003** [DiscipleD/blog#1]
还有我认为你vuex这一块写的不够好，并不是什么状态或者异步请求都要放到vuex里面绕一大圈的，当多个组件共享一个状态的时候才用到vuex

**Comment by DiscipleD** [comment]
memory-fs 自带是什么意思？

嗯，vuex 那块的的确有许多配置可以不走 vuex，但把 vuex 看成整个应用的数据层，页面都是通过配置显示的就是另一个角度了。

欢迎提更多的意见和建议。

**Comment by jsm1003** [comment]
https://vuex.vuejs.org/zh-cn/state.html 看最后一段话，

**Comment by DiscipleD** [comment]
之前的回答就说了，Blog 的场景下的确是可以不用 vuex，使用 vuex 是增加了复杂度，但层次就更清晰了。
