### ISSUE TITLE
项目无法运行

### ISSUE THREAD

**Issue by jsgr** [DiscipleD/blog#2]
请问下，拷贝您的项目，安装依赖之后无法运行，试过其他命令也是无效的，请问还需进行什么操作

**Comment by DiscipleD** [comment]
能否提供一下错误信息。

**Comment by jsgr** [comment]
已经安装好依赖包了，npm start 之后  ，报错信息是这样的
> disciple.ding-blog@2.6.2 copy:posts D:\Vue\DiscipleD_blog
> npm run clean && mkdir build && mkdir build/server && mkdir build/server/data && cp -r src/server/data/posts build/server/data


> disciple.ding-blog@2.6.2 clean D:\Vue\DiscipleD_blog
> rm -rf build

▒▒▒▒▒﷨▒▒▒▒ȷ▒▒

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "copy:posts"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! disciple.ding-blog@2.6.2 copy:posts: `npm run clean && mkdir build && mkdir build/server && mkdir build/server/data && cp -r src/server/data/posts build/server/data`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the disciple.ding-blog@2.6.2 copy:posts script 'npm run clean && mkdir build && mkdir build/server && mkdir build/server/data && cp -r src/server/data/posts build/server/data'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the disciple.ding-blog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && mkdir build && mkdir build/server && mkdir build/server/data && cp -r src/server/data/posts build/server/data
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs disciple.ding-blog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls disciple.ding-blog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Vue\DiscipleD_blog\npm-debug.log
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: D:\Vue\DiscipleD_blog\build/**/*
[nodemon] starting `npm run copy:posts && babel src/server -w -d build/server --no-babelrc --presets=es2015,stage-3 & nodemon --watch build --delay 2 build/server/server.js build/server/server.js build/server/server.js build/server/server.js build/server/server.js build/server/server.js build/server/server.js build/server/server.js`

> disciple.ding-blog@2.6.2 copy:posts D:\Vue\DiscipleD_blog
> npm run clean && mkdir build && mkdir build/server && mkdir build/server/data && cp -r src/server/data/posts build/server/data

尝试过 npm run dev 并不生效

**Comment by DiscipleD** [comment]
好吧...windows 环境，里面一些 linux 的命令执行不了

**Comment by DiscipleD** [comment]
试试虚拟机，或者 docker 环境吧
