### ISSUE TITLE
D.D Blog bug

### ISSUE THREAD

**Issue by hakonleung** [DiscipleD/blog#3]
你好，今天有幸查阅你的博客，发现有一个bug，缩小浏览器窗口后导航栏变为可折叠，如果此时点击menu将导航栏折叠，再将窗口大小复原，导航栏的按钮不会再出现。

**Comment by DiscipleD** [comment]
感谢指出，我会尽快修复。🙂

**Comment by DiscipleD** [comment]
Fixed.
