### ISSUE TITLE
老哥 运行你的项目之后 出现好多模块找不到  怎么解决

### ISSUE THREAD

**Issue by ko00wu** [DiscipleD/blog#4]
比如
找不到
./middleware
./graphql
等等

**Comment by DiscipleD** [comment]
麻烦贴下详细的错误信息。

**Comment by KloveML** [comment]
不好意思 前几天工作上有点事 忘了回你  今天整理一下回你

**Comment by KloveML** [comment]
不好意思 前几天工作上有点事  没来得及回你 先整理一下运行出错的问题
1.如果没有build文件，执行会报以下错

**Comment by ko00wu** [comment]
不好意思  前几天工作上有点忙  忘忙了回你 今天整理一下运行出错的问题 
1.如果没有build文件夹，运行会提示没有build文件夹，然后报以下错，我想应该不正常
![1518242455190](https://user-images.githubusercontent.com/20701247/36059070-dd37d27e-0e6a-11e8-85d0-5acf96ead20f.jpg)
2.如果有build文件夹，会提示没有./middleware这个文件夹
![image](https://user-images.githubusercontent.com/20701247/36059073-feb3f946-0e6a-11e8-850d-8db162ca6807.png)

**Comment by DiscipleD** [comment]
第一个可能是你运行命令出错了，用 npm start 应该不会遇到了。

第二个是正常的，因为 node 端的 ts 编译是异步的，不要手动终止。文件编译好之后，nodemon 会重启的，如果启动不起来再给我留言。

启动脚本之后我会试着简化一下。
